# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-07-04 05:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinyUrlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.URLField()),
                ('long_url', models.URLField()),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2020, 7, 7, 5, 20, 55, 671734))),
            ],
        ),
    ]
